version: '3.8'

services:
  app:
    image: mcr.microsoft.com/devcontainers/universal:linux # 앱 컨테이너의 기본 이미지
    volumes:
      - ..:/workspaces:cached # 현재 워크스페이스를 이 컨테이너의 /workspaces에 마운트
    # user: codespace는 devcontainer.json의 "remoteUser"가 처리하므로 여기에 명시하지 않습니다.
    command: sleep infinity # 컨테이너가 종료되지 않고 계속 실행되도록 유지하는 가장 간단한 방법
    ports:
      - "3000:3000"
      - "5000:5000"

  db:
    image: mongo:6.0 # MongoDB 6.0 공식 이미지
    restart: unless-stopped # 컨테이너 중지 시 자동으로 재시작
    volumes:
      - dbdata:/data/db # MongoDB 데이터 영속성을 위한 볼륨 마운트
    ports:
      - "27017:27017" # MongoDB 기본 포트

volumes:
  dbdata: # MongoDB 데이터를 위한 이름 있는 볼륨 정의 (컨테이너가 사라져도 데이터는 유지)