version: '3.8'

services:
  app:
    image: mcr.microsoft.com/devcontainers/universal:linux # 앱 컨테이너는 Universal 이미지 사용
    volumes:
      - ..:/workspaces:cached # 현재 워크스페이스를 마운트
    user: codespace # devcontainer.json의 remoteUser와 일치시킵니다.
    # 'features' 섹션은 여기(docker-compose.yml)에서 완전히 제거해야 합니다!
    command: /bin/sh -c "while sleep 1000; do :; done" # 컨테이너가 계속 실행되도록 더미 명령어
    ports:
      - "3000:3000"
      - "5000:5000"

  db:
    image: mongo:6.0 # MongoDB 6.0 공식 이미지 사용
    restart: unless-stopped # 컨테이너 중지 시 재시작
    volumes:
      - dbdata:/data/db # 데이터 영속성을 위한 볼륨 마운트
    ports:
      - "27017:27017" # MongoDB 기본 포트

volumes:
  dbdata: # MongoDB 데이터 저장을 위한 볼륨 정의